FROM mcr.microsoft.com/powershell:7.4-ubuntu-22.04
ENV ATTESTATION_MODULE="StateEngine" RUNTIME_AUTH="Robdoe" SYSTEM_STATE="CONTAINERIZED_GLYPHIC" DOCKER_ENGINE_STATE="DAEMON_OFFLINE_FALLBACK"
COPY . /workspace
WORKDIR /workspace
CMD ["pwsh"]
